services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token
      - key: CHANNEL_USERNAME
        value: @buxgalterlik_xizmatlari
      - key: GROUP_ID
        value: -1002407659338
      - key: ADMIN_ID
        value: 734139298
      - key: DB_NAME
        value: telegram_vg4s
      - key: DB_USER
        value: post
      - key: DB_PASSWORD
        value: tiHjT2J1dBFDwohfIXFaR1f1I38smNU2
      - key: DB_HOST
        value: postgresql://post:tiHjT2J1dBFDwohfIXFaR1f1I38smNU2@dpg-d0gafcjuibrs73fe5i9g-a/telegram_vg4s
      - key: DB_PORT
        value: 5432